[exit_codes]
# optional; sound to play for commands with exit code 0
# if not set, ting will use builtin sound
success = "~/sounds/success.wav"
# optional; sound to play for commands with exit code other than 0
# if not set, ting will use builtin sound
error = "~/sounds/error.wav"

# these need to be set up if you want to use custom cues as follows
# `ting play --cue build-success`
# otherwise these are not needed
[cues]
build-success = "~/sounds/custom/build-success.wav"
build-fail = "~/sounds/custom/build-fail.wav"
