[package]
name = "ting"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dhth/ting"
description = "audio feedback for command exit codes"
homepage = "https://github.com/dhth/ting"
keywords = [
    "cli",
    "audio",
    "notifications",
]
categories = [
    "command-line-utilities",
]
exclude = [
    ".github",
    "clippy.toml",
    "deny.toml",
    "docker-compose.yml",
    "justfile",
]

[dependencies]
anyhow = "1.0.98"
rodio = { version = "0.21.1", default-features = false, features = ["playback", "tracing", "wav"] }

[dev-dependencies]
insta-cmd = "0.6.0"
