[package]
name = "ting"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dhth/ting"
description = "audio feedback on the command line"
homepage = "https://tools.dhruvs.space/ting/"
keywords = [
    "cli",
    "audio",
    "notifications",
]
categories = [
    "command-line-utilities",
]
exclude = [
    ".github",
    "clippy.toml",
    "deny.toml",
    "docker-compose.yml",
    "justfile",
]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
etcetera = "0.11.0"
rodio = { version = "0.22.1", default-features = false, features = ["mp3", "playback", "tracing", "wav"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "0.9.11", features = ["parse"] }

[dev-dependencies]
insta = { version = "1.46.2", features = ["yaml"] }
insta-cmd = "0.6.0"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
dbg_macro = "deny"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
