name: audit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 2,6'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-deny
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: EmbarkStudios/cargo-deny
      - name: cargo deny
        run: cargo deny check
